NDefines.NDiplomacy.BREAK_TRUCE_PRESTIGE_PERC_COST = 0.75
NDefines.NDiplomacy.BREAK_TRUCE_PRESTIGE_COST = 0 --v11 removed base prestige cost
NDefines.NDiplomacy.MONTHS_PER_SUCCESSION_CB = 60 -- Number of months a succession CB lasts
NDefines.NDiplomacy.ATTACKING_SOMEONE_CRUSADING_PIETY_COST = 400 -- Piety hit for attacking someone crusading v11 increased from 200
NDefines.NDiplomacy.ATTACKING_SOMEONE_DEFENDING_AGAINST_OTHER_RELIGIOUS_GROUP_PIETY_COST = 350 -- Piety hit for attacking someone who is defending against other religious group v11 increased from 200
NDefines.NDiplomacy.ATTACKER_CALL_DECLINE_COST = 200 -- Prestige cost for refusing to join an offensive war v11 increased to 200
NDefines.NDiplomacy.DEFENDER_CALL_DECLINE_COST = 200 -- Prestige cost for refusing to join a defensive war v11 150 to 400
NDefines.NDiplomacy.PAPAL_INVEST_PIETY_COST_MULT = 0.5 -- The effect of Papal investiture on the piety cost of the special Papal actions
NDefines.NDiplomacy.SHORT_REIGN_YEARS_END = 8 -- notes:x-2 opinion per year v10nincreased from 9 to 15 v11 increased to 20 v12 reduced to 8 (with -5 per year) v12 increased / Numahr: decreased to 8 based on user feedback
NDefines.NDiplomacy.LONG_REIGN_YEARS_START = 15 -- v10n decreased from 20 to 15 v11 corrected computation. Gap is 5 (vanilla 20-9=11). v11 starts at 15 (gap of 7 years) v12 start 20, gap 10 v14 start 15, gap 5
NDefines.NDiplomacy.SHORT_REIGN_OPINION_MULT = 5 -- v12 (-5 x 8 per year with DivineRight = 0) v14 reduced to 4 / Numahr: increased back to 5 as all SELIN metrics are based on this
NDefines.NDiplomacy.DOW_ON_ALLY_PRESTIGE_COST = 500 -- v11 increased from 150 to 500
NDefines.NDiplomacy.RELEASE_PRISONER_PIETY = 10 -- vanilla 5
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_KING_MULT = 2.0 -- Extra Max Demesne Size from the ruler's rank v11 reduced from 3
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_EMPEROR_MULT = 3.0 -- Extra Max Demesne Size from the ruler's rank v11 reduced from 4
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_STEWARDSHIP_MULT = 0.15 -- Extra Max Demesne Size from ruler and spouse intrigue v11 decreased
NDefines.NDiplomacy.MAX_DUCHIES_LEGALLY_HELD = 3 -- Max duchies that a king or above can hold before vassals start getting angry
NDefines.NDiplomacy.ASSASSINATION_COST_RANK_MULT = 50 -- Max duchies that a king or above can hold before vassals start getting angry
NDefines.NDiplomacy.PAGAN_PEACE_MONTHS = 36 -- Months before the Peace Prestige loss kicks in for certain Pagan religions v12 adjusted from 24 to 36
NDefines.NDiplomacy.PAGAN_PEACE_MONTHLY_PRESTIGE_LOSS = 1.0 -- Prestige loss for being at peace, for certain Pagan religions --v12 adjusted from -2 to -1
NDefines.NDiplomacy.PRESTIGE_OPINION_DIV = 200 -- Divider for prestige to vassal opinion (5x higher effect for negative prestige) --v12 tweaked to make 6k necessary for max opinion
NDefines.NDiplomacy.PRESTIGE_OPINION_MAX = 30 -- Max opinion impact of prestige (positive OR negative) --v11 increased 20->30
NDefines.NDiplomacy.PIETY_OPINION_DIV = 50 -- Divider for piety to church opinion -- v12 increased divider to 100, so 50 piety = +1
NDefines.NDiplomacy.PIETY_OPINION_MAX = 20 -- Max opinion impact of piety (positive OR negative)	--
NDefines.NDiplomacy.MIN_PREP_INV_TARGET_HOLDINGS = 0 -- The target must control at least this many holdings within the target kingdom to be a valid prepared invasion target --v12 reduced from 9 to 0
NDefines.NDiplomacy.MAX_PREP_INV_TARGET_HOLDINGS = 60 -- The target must control at the most this many holdings within the target kingdom to be a valid prepared invasion target --v12 reduced to half --Numahr: increased since prepared invasions have spiritual power law restrictions
NDefines.NDiplomacy.MAX_PREP_INV_TARGET_HOLDINGS = 60 -- The target must control at the most this many holdings within the target kingdom to be a valid prepared invasion target --v12 reduced to half --Numahr: increased since prepared invasions have spiritual power law restrictions
NDefines.NDiplomacy.MAX_PREP_INV_ATTACKER_HOLDINGS = 60 -- The attacker must have fewer Holdings than this in the realm (disallow Prepared Invasions for rulers who are already very powerful) --Numahr: increased since prepared invasions have spiritual power law restrictions
NDefines.NDiplomacy.PREP_INV_REQ_PRESTIGE = 250 -- Need to have this much Prestige to prepare an invasion --v12 Aside from 500 prestige, 250 piety is spent due to Populist Souls concept)
NDefines.NDiplomacy.BASE_REVOLT_CHANCE_MOD = 225 -- Pre Old Gods rebel spawn chance modifier (fires on_rebel_revolt) : lower means fewer revolts. MUST NOT BE ZERO. --v12 modified to be 30% of vanilla (1k) 21 reduced 12% further
NDefines.NDiplomacy.TOG_REVOLT_CHANCE_MOD = 75 -- Old Gods rebel spawn chance modifier (fires on_rebel_revolt) : lower means fewer revolts. MUST NOT BE ZERO. -- v12 reduced incidence to half of vanilla (200) 12a reduced 25% further
NDefines.NDiplomacy.MAX_DIPLO_DISTANCE = 500					-- Most diplomacy is disallowed if two rulers are too distant v14 reduced from 700 to 500
NDefines.NDiplomacy.MAX_DIPLO_DISTANCE_SAME_RELIGION = 500		-- Bonus to max diplo distance for being of the same religion v14 boosted to 500 from 100
NDefines.NDiplomacy.MAX_DIPLO_DISTANCE_SAME_RELIGION_GROUP = 30 -- Bonus to max diplo distance for being of the same religion group v14 boosted to 300 from 0
NDefines.NDiplomacy.MAX_DIPLO_DISTANCE_SAME_CULTURE = 500 		-- Bonus to max diplo distance for being of the same culture v14 boosted too 500 from 100
NDefines.NDiplomacy.MAX_DIPLO_DISTANCE_SAME_CULTURE_GROUP = 300 -- Bonus to max diplo distance for being of the same culture group boosted to 300 from 100 
NDefines.NDiplomacy.IMPRISON_CHARACTER_INTERACTION_PIETY = 0
NDefines.NDiplomacy.IMPRISON_CHARACTER_INTERACTION_PRESTIGE = 10
NDefines.NDiplomacy.IMPRISON_CHARACTER_INTERACTION_MUST_HAVE_COST = 1				-- Is having prestige/piety >= cost required for this action?
NDefines.NDiplomacy.RELEASE_FROM_PRISON_INTERACTION_PIETY = -10
NDefines.NDiplomacy.RELEASE_FROM_PRISON_INTERACTION_PRESTIGE = -5
NDefines.NDiplomacy.EXECUTE_IMPRISONED_INTERACTION_PIETY = 0
NDefines.NDiplomacy.EXECUTE_IMPRISONED_INTERACTION_PRESTIGE = 25
NDefines.NDiplomacy.EXECUTE_IMPRISONED_INTERACTION_MUST_HAVE_COST = 1			-- Is having prestige/piety >= cost required for this action?
NDefines.NDiplomacy.EXILE_IMPRISONED_INTERACTION_PIETY = 0
NDefines.NDiplomacy.EXILE_IMPRISONED_INTERACTION_PRESTIGE = 100
NDefines.NDiplomacy.EXILE_IMPRISONED_INTERACTION_MUST_HAVE_COST = 1				-- Is having prestige/piety >= cost required for this action?
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_PIETY = 25
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_PRESTIGE = 10
NDefines.NDiplomacy.INVITE_TO_COURT_INTERACTION_MONEY = 10
NDefines.NDiplomacy.INVITE_TO_COURT_INTERACTION_PRESTIGE = 25
NDefines.NDiplomacy.TRANSFER_VASSAL_INTERACTION_MONEY = 10
NDefines.NDiplomacy.TRANSFER_VASSAL_INTERACTION_PRESTIGE = 10
NDefines.NDiplomacy.CLAIM_TITLE_INTERACTION_PRESTIGE = 100
NDefines.NDiplomacy.REVOKE_TITLE_INTERACTION_MONEY = 25
NDefines.NDiplomacy.REVOKE_TITLE_INTERACTION_PRESTIGE = 50
NDefines.NDiplomacy.AWARD_HONORARY_TITLE_INTERACTION_MONEY = 10
NDefines.NDiplomacy.SEND_ASSASSIN_INTERACTION_PRESTIGE = 50
NDefines.NDiplomacy.SEND_GIFT_INTERACTION_PRESTIGE = 5
NDefines.NDiplomacy.OFFER_VASSALIZATION_INTERACTION_PIETY = 10
NDefines.NDiplomacy.OFFER_VASSALIZATION_INTERACTION_PRESTIGE = 30
NDefines.NDiplomacy.ASK_FOR_VASSALIZATION_INTERACTION_MONEY = 25
NDefines.NDiplomacy.ASK_FOR_VASSALIZATION_INTERACTION_PRESTIGE = 25
NDefines.NDiplomacy.ARRANGE_BETROTHAL_INTERACTION_MONEY = 10
NDefines.NDiplomacy.ARRANGE_BETROTHAL_INTERACTION_PIETY = 25
NDefines.NDiplomacy.ARRANGE_BETROTHAL_INTERACTION_PRESTIGE = 10
NDefines.NDiplomacy.BREAK_BETROTHAL_INTERACTION_PIETY = 150
NDefines.NDiplomacy.BREAK_BETROTHAL_INTERACTION_PRESTIGE = 150
NDefines.NDiplomacy.OFFER_SUCCESSION_MARRIGE_INTERACTION_PIETY = 5
NDefines.NDiplomacy.OFFER_SUCCESSION_MARRIGE_INTERACTION_PRESTIGE = 5
NDefines.NDiplomacy.OFFER_MARRIGE_INTERACTION_PIETY = 5
NDefines.NDiplomacy.OFFER_MARRIGE_INTERACTION_PRESTIGE = 5
NDefines.NDiplomacy.RANSOM_CHARACTER_INTERACTION_PRESTIGE = 5
NDefines.NDiplomacy.EDUCATE_CHARACTER_INTERACTION_PRESTIGE = 5
NDefines.NDiplomacy.ABANDON_AMBITION_INTERACTION_PRESTIGE = 50
NDefines.NDiplomacy.STOP_BACKING_AMBITION_INTERACTION_PRESTIGE = 20
NDefines.NDiplomacy.GRANT_LANDED_TITLE_INTERACTION_MONEY = 5
NDefines.NDiplomacy.GRANT_LANDED_TITLE_INTERACTION_PRESTIGE = 5
NDefines.NDiplomacy.APPOINT_TO_OFFICE_INTERACTION_MONEY = 5
NDefines.NDiplomacy.APPOINT_TO_OFFICE_INTERACTION_PRESTIGE = 5
NDefines.NDiplomacy.RESIGN_FROM_OFFICE_INTERACTION_PRESTIGE = 50
NDefines.NDiplomacy.ASK_FOR_INVASION_INTERACTION_THRESHOLD_FOR_NO = 0
NDefines.NDiplomacy.ASK_FOR_INVASION_INTERACTION_THRESHOLD_FOR_YES = 0
NDefines.NDiplomacy.ASK_FOR_DIVORCE_INTERACTION_THRESHOLD_FOR_NO = 0
NDefines.NDiplomacy.ASK_FOR_DIVORCE_INTERACTION_THRESHOLD_FOR_YES = 0
NDefines.NDiplomacy.ASK_FOR_EXCOMMUNICATION_INTERACTION_PIETY = 250
NDefines.NDiplomacy.ASK_FOR_EXCOMMUNICATION_INTERACTION_THRESHOLD_FOR_NO = 0
NDefines.NDiplomacy.ASK_FOR_EXCOMMUNICATION_INTERACTION_THRESHOLD_FOR_YES = 0
NDefines.NDiplomacy.CALL_ALLY_INTERACTION_PRESTIGE = 25
NDefines.NDiplomacy.ASK_TO_LIFT_EXCOMMUNICATION_INTERACTION_PIETY = 150
NDefines.NDiplomacy.ASK_TO_LIFT_EXCOMMUNICATION_INTERACTION_THRESHOLD_FOR_NO = 0
NDefines.NDiplomacy.ASK_TO_LIFT_EXCOMMUNICATION_INTERACTION_THRESHOLD_FOR_YES = 0
NDefines.NDiplomacy.ASK_TO_RANSOM_CHARACTER_INTERACTION_PRESTIGE = 10
NDefines.NDiplomacy.ASK_TO_JOIN_WAR_INTERACTION_PRESTIGE = 10
NDefines.NDiplomacy.RELEASE_VASSAL_INTERACTION_PRESTIGE = 25
NDefines.NDiplomacy.PREPARE_INVASION_INTERACTION_PIETY = 250
NDefines.NDiplomacy.PREPARE_INVASION_INTERACTION_PRESTIGE = 0
NDefines.NDiplomacy.MAKE_CONSORT_INTERACTION_PRESTIGE = 5
NDefines.NDiplomacy.RETRACT_VASSAL_INTERACTION_MONEY = 10
NDefines.NDiplomacy.RETRACT_VASSAL_INTERACTION_PRESTIGE = 50
NDefines.NCharacter.CHANGE_AMBITION_YEARS = 1						-- Delay between being able to pick a new ambition of plot after cancelling
NDefines.NCharacter.CHANGE_FOCUS_YEARS = 4							-- Delay between being able to change focus
NDefines.NCharacter.PRESTIGE_FROM_DYNASTY_ON_BIRTH_DIV = 50		-- Newly born characters get the dynasty prestige of their mother and father divided by this as their starting prestige --v12 increased from 10 to 50
NDefines.NCharacter.PRESTIGE_FROM_DYNASTY_ON_MARRIAGE_DIV = 50 	-- Characters get the dynasty prestige of the spouse divided by this on marriage --v12 increased from 20 to 50
NDefines.NCharacter.ASSIGN_ACTION_DAYS = 90 						-- Days before a Councillor can be assigned a new job in a county
NDefines.NCharacter.MARRIAGE_TIER_DIFF_PRESTIGE_MULT = 10 			-- Prestige multiplier from marrying below or above your rank. -v12 halved
NDefines.NCharacter.RAISED_TROOPS_VASSAL_OPINION_DAYS = 85			-- After 73 days of having their troops raised, vassals will get -1 opinion more of you v10n increased to 100 days (3 months and a week approximately) v11 increased to 85
NDefines.NCharacter.MUSLIM_NUM_WIVES_MONTHLY_PRESTIGE = 0.15		-- The prestige effect from each extra or lacking expected wife --v12 reduced from 0.4 to 0.15
NDefines.NCharacter.PORTRAIT_MID_AGE_THRESHOLD = 32				-- Middle age switch for character portraits
NDefines.NCharacter.COURT_SIZE_CHILD_PENALTY_THRESHOLD = 25
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_10 = 0				-- Natural deaths per decade out of 10000 people: Age 10-19
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_20 = 0				-- Natural deaths per decade out of 10000 people: Age 20-29
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_30 = 0				-- Natural deaths per decade out of 10000 people: Age 30-39
NDefines.NCharacter.SECONDARY_SPOUSE_FERTILITY_MULT = 0.25			-- Applied to fertility of secondary spouses and concubines
NDefines.NCharacter.NOT_SPOUSE_FERTILITY_MULT = 0.25				-- Applied to fertility when the two characters are not married
NDefines.NCharacter.EARLY_PORTRAIT_AND_UNIT_BEFORE_YEAR = 1200		-- Before this date, early versions of Units and Portraits will be used if available
NDefines.NCharacter.LATE_PORTRAIT_AND_UNIT_AFTER_YEAR = 1450		-- After this date, late versions of Units and Portraits will be used if available
NDefines.NTitle.BARON_AS_VASSAL_PRESTIGE = 0.0
NDefines.NTitle.COUNT_AS_VASSAL_PRESTIGE = 0.0
NDefines.NTitle.DUKE_AS_VASSAL_PRESTIGE = 0.05
NDefines.NTitle.KING_AS_VASSAL_PRESTIGE = 0.25
NDefines.NTitle.BARON_TITLE_PRESTIGE = 0.0
NDefines.NTitle.COUNT_TITLE_PRESTIGE = 0.0
NDefines.NTitle.DUKE_TITLE_PRESTIGE = 0.05
NDefines.NTitle.KING_TITLE_PRESTIGE = 0.1
NDefines.NTitle.EMPEROR_TITLE_PRESTIGE = 0.3
NDefines.NTitle.DUKE_LANDLESS_SON_PRESTIGE = 0.25
NDefines.NTitle.KING_LANDLESS_SON_PRESTIGE = 0.5
NDefines.NTitle.EMPEROR_LANDLESS_SON_PRESTIGE = 0.75
NDefines.NTitle.KING_TITLE_DYNASTY_PRESTIGE = 15
NDefines.NTitle.EMPEROR_TITLE_DYNASTY_PRESTIGE = 25
NDefines.NTitle.DUKE_GRANT_TO_CHURCH_PIETY = 75
NDefines.NTitle.KING_GRANT_TO_CHURCH_PIETY = 100
NDefines.NTitle.EMPEROR_GRANT_TO_CHURCH_PIETY = 500
NDefines.NTitle.DUKE_CREATION_COST = 150
NDefines.NTitle.KING_CREATION_COST = 300
NDefines.NTitle.EMPEROR_CREATION_COST = 500
NDefines.NTitle.BARON_CREATION_PRESTIGE = 100 -- Granted when building a new settlement
NDefines.NTitle.DUKE_CREATION_PRESTIGE = -250
NDefines.NTitle.KING_CREATION_PRESTIGE = -500
NDefines.NTitle.EMPEROR_CREATION_PRESTIGE = -1000
NDefines.NTitle.DUKE_DESTRUCTION_PRESTIGE_COST = 500
NDefines.NTitle.KING_DESTRUCTION_PRESTIGE_COST = 1000
NDefines.NTitle.EMPEROR_DESTRUCTION_PRESTIGE_COST = 2500
NDefines.NTitle.BARON_REVOKE_PRESTIGE_COST = 100
NDefines.NTitle.COUNT_REVOKE_PRESTIGE_COST = 200
NDefines.NTitle.DUKE_REVOKE_PRESTIGE_COST = 500
NDefines.NTitle.KING_REVOKE_PRESTIGE_COST = 1000
NDefines.NTitle.BARON_GRANT_DECADENCE_RED = 0.015
NDefines.NTitle.COUNT_GRANT_DECADENCE_RED = 0.03
NDefines.NTitle.DUKE_GRANT_DECADENCE_RED = 0.06
NDefines.NTitle.KING_GRANT_DECADENCE_RED = 0.2
NDefines.NTitle.EMPEROR_GRANT_DECADENCE_RED = 0.5
NDefines.NTitle.DE_JURE_ASSIMILATION_YEARS = 150			-- Duchies a under the de facto control of another kingdom will change de jure liege after this many years v11 increased by 2.5x v12 modified to 150 years
NDefines.NTitle.EMPIRE_DE_JURE_ASSIMILATION_YEARS = 50		-- Kingdoms under the de facto control of another empire will change de jure liege after this many years v11 increased 2x v12 reduced to 50 years
NDefines.NTitle.ALLOW_DE_JURE_ASSIMILATION_ANYWHERE = 0	-- If set to 0, will only assimilate duchy titles which contain the assimilating Kingdom's capital or border existing de jure land of that title
NDefines.NTitle.REQ_DUCHIES_FOR_KINGDOM_CREATION = 1 		-- Number of held duchies required to create a kingdom (for rulers who are not already kings or emperors)
NDefines.NTitle.REQ_KINGDOMS_FOR_EMPIRE_CREATION = 1 		-- Number of held kingdoms required to create an Empire (for rulers who are not already emperors) -- made into 1 for now 
NDefines.NTitle.TITULAR_TITLE_CREATION_COST_MULT = 0.75	-- Titular titles are more expensive to create -v11 made 25% more expensive --v12 reversed policy now 25% cheaper
NDefines.NTitle.ENFORCE_ONE_OF_EACH_HOLDING = 0			-- Require players to build at least one City, Temple and Castle in each province --v11 disabled
NDefines.NTitle.DEJURE_COUNTY_LIMIT_TO_CREATE = 0.5		-- Fraction of de jure counties that you must control to create a non-imperial title v11 changed to 50% (so a 4 county duchy that doesn't currently exist can be easily made with just half)
NDefines.NTitle.DEJURE_COUNTY_LIMIT_TO_USURP = 0.75			-- Fraction of de jure counties that you must control to usurp a non-imperial title v11 changed to 75% (so a 4 county duchy requires at 3 to be stolen)
NDefines.NTitle.EMPIRE_DEJURE_COUNTY_LIMIT_TO_CREATE = 0.6	-- Fraction of de jure counties that you must control to create an imperial title v11 changed to 60% (so creating the empire title from de jure land still requires hegemony)
NDefines.NTitle.EMPIRE_DEJURE_COUNTY_LIMIT_TO_USURP = 0.4	-- Fraction of de jure counties that you must control to usurp an imperial title	 v11 changed to 40% (so usurping it from weakend vestigial empires is a lot easier)
NDefines.NReligion.CREATE_ANTIPOPE_PRESTIGE_COST = 800
NDefines.NReligion.EXCOM_MIN_AUTHORITY = 0.3
NDefines.NReligion.INVASION_MIN_AUTHORITY = 0.4
NDefines.NReligion.KINGDOM_CREATION_PIETY_COST = 150 -- v11 edited v12 reduced
NDefines.NReligion.EMPIRE_CREATION_PIETY_COST = 350 -- v11 edited to 500 (authority cost added) v12 reduced
NDefines.NReligion.REFORM_RELIGION_MIN_HOLY_SITES = 4				-- Number of holy sites you must control to reform a pagan faith
NDefines.NReligion.AUTHORITY_FROM_ORG_RELIGION = 0.2				-- Authority from being an organized religion§ki§
NDefines.NReligion.ELECTOR_TITLE_CULTURE_GROUP_FACTOR = 0
NDefines.NReligion.ELECTOR_TITLE_CULTURE_FACTOR = 0
NDefines.NReligion.ELECTOR_FAMOUS_DYNASTY_FACTOR = 1
NDefines.NReligion.REPUBLIC_CAPITAL_CITY_TAX_BONUS = 1.5			-- Duke or above tier Republics receive a tax bonus for their capital city v11 increased from 1
NDefines.NEconomy.DECADENCE_MODIFIER = 0.5						-- Maximum effect of decadence, positive for low dec, negative for high v11 increased to 50%
NDefines.NEconomy.DECADENCE_PER_WEEK_OF_COMBAT = -0.075			-- Decadence lost per 7 days of combat, for each participant in the combat v11 increased to 0.075 from 0.04
NDefines.NEconomy.DECADENCE_PER_WEEK_OF_SIEGE = -0.015			-- Decadence lost per 7 days of siege, for each participant in the siege v11 increased to 0.015 from 0.08
NDefines.NEconomy.TRADE_CONNECTED_TO_CAPITAL_BONUS = 0.5			-- Bonus to trade post income when connected to capital - v12 increased from 0.4 to 0.5
NDefines.NEconomy.TRADE_POST_COST_INC_DIST = 0.006				-- The % increase in cost due to distance to closest connected province v10m increased from 0.3% to 0.75% v11 increased to 0.6%
NDefines.NEconomy.TRADE_POST_OPINION_EFFECT = 0.5				-- The bonus or penalty depending on topliege opinion v10l increased to 0.5 v10m reduced to 0.2 v11 increased to 0.25 v11 increased to 0.5
NDefines.NEconomy.MIN_TRADETECH_LEVEL_FOR_TPS = 1				-- Minimum tech level needed to build trade posts v12 reduced to level 1 v12b reduced to 0 v13 reverted to 1 because it seems hardcoded
NDefines.NEconomy.TRADETECH_LEVEL_FOR_BASE_TPS = 1 --v12 reduced to level 1
NDefines.NEconomy.PATRICIAN_CAMPAIGN_FUND_FACTOR = 4				-- The effect of money in the Campaign Fund on Doge elections (money * factor) v11 lowered from 5 to 2 (because the AI doesn't use this feature much, if at all) v12a increased to 4 to be slightly close to vanilla but less
NDefines.NEconomy.PATRICIAN_PRESTIGE_RESPECT_FACTOR = 5			-- The effect of Prestige on the Respect value for Doge elections (prestige * factor) v11 increased to 3 v12a made authority have more impact
NDefines.NEconomy.DOGE_SUCC_RANDOM_FACTOR = 1000					-- The random Respect factor on actual Doge succession v11 doubled
NDefines.NEconomy.MERCHANT_REPUBLIC_SALARY_MULT = 1.5				-- Councillor salaries in Merchant Republics are multiplied by this v11 increased v12 reduced to 1.5 because default salaries increased
NDefines.NEconomy.PATRICIAN_FAMILY_SHARES_HEAD = 50				-- Monthly Patrician Income, number of shares for the Patrician himself v11 doubled 
NDefines.NEconomy.PATRICIAN_FAMILY_SHARES_REST = 5				-- Monthly Patrician Income, number of shares for the Patrician's distant relatives
NDefines.NEconomy.PATRICIAN_CITY_TAX_MULT = 0.5					-- Patricians don't pay normal City Tax to their liege... (CFixedPoint64) v12 reduced to 33.3% v12c reverted to 50%
NDefines.NEconomy.OVER_MAX_DEMESNE_TAX_PENALTY = 0.25			-- Percent penalty per county over the limit
NDefines.NEconomy.TAX_TO_LOOT_MULTIPLIER = 2.0				-- Lootable gold per tax  v12 reduced from 100% to 50% to deemphasize looting for gold v14 reverted to vanilla 
NDefines.NEconomy.FORT_LOOT_DEFENCE_MULTIPLIER = 0.25				-- Loot protected gold per fortlevel v12 reduced from 4 to 0.5 to make raiding easier v12(exp) to 0.2 v14 tweaked
NDefines.NEconomy.LOOTABLE_GOLD_REGROWTH = 0.05					-- Percent of max lootable gold that regrows every month  v12 reduced from 2.5% to 1% to deemphasize "farming" v14 changed approach to double of vanilla to make it recover faster
NDefines.NEconomy.LOOT_PERCENT_PER_LOOTTICK = 0.07				-- Percent of max lootable gold that is looted each loot tick v12 reduced from 4% to 1% (previously 4% per 4 days) v14 increased to 7% per week (experiment in lag reduction)
NDefines.NEconomy.LOOTER_SHIP_MAINT_MULT = 0.25					-- Religions that have looting have lower ship maintenance costs v12 increased from 10% to 25%
NDefines.NEconomy.LOOT_PRESTIGE_MULT = 1.25						-- Whenever you gain loot you also get prestige related to the loot v12 buffed by 50% to emphasize authority focus of raiding v14 reduced buff to 25% for a while to compensate for increased raiding rewards
NDefines.NEconomy.LOOT_EVERY_X_DAYS = 7							-- Loot every this many days v12 halved from 4 to 1 v14 increased to a week (experimental lag reduction)
NDefines.NEconomy.LOOT_IDEAL_MIN_TROOPS = 100					-- Minimum troops for maximum loot, less than this scales down the amount looted --v12 reduced from 500 to 100 to reflect smaller LI sizes
NDefines.NEconomy.BUILDING_COST_MULT = 0.1						-- Increases build cost of all buildings --v12 properly implemented the 50% discount v12a-temp: removed discount to see if it will help alleviate slowdown v12b implemented a 10% discount
NDefines.NDecadence.BASE_EMPEROR_GAIN = 0.45
NDefines.NDecadence.BASE_KING_GAIN = 0.36
NDefines.NDecadence.BASE_DUKE_GAIN = 0.24
NDefines.NDecadence.BASE_COUNT_GAIN = 0.18
NDefines.NDecadence.BASE_BARON_GAIN = 0.09
NDefines.NDecadence.BASE_UNLANDED_GAIN = 0.045
NDefines.NMilitary.MORALE_COLLAPSE_THRESHOLD = 0.2				-- Threshold before unit runs away --v12 reduced to 10% v15 increased to 20% (vanilla 25)
NDefines.NMilitary.TROOP_KILL_FACTOR = 0.01						-- Affects the death rate in combats(higher gives bigger losses) > v10 increased from 1.5 to 2  v12 reduced to .01 v12a reduced to .005 (vanilla 0.15) v12c increased to .009 v14 rebalanced to .01
NDefines.NMilitary.NUMBER_OF_RETREAT_DAYS = 8						-- Number of days before you retreat successfully --v12 doubled
NDefines.NMilitary.OTHER_TERRITORY_LEVY_RETURN_PERCENT = 0.7		-- Percent of subunit that returns to levy when unit is disbanded in non-friendly territory v10 increased to limit ai handicap
NDefines.NMilitary.HOLDING_LEVY_SIZE_OWNER_MARTIAL_BASE = 0.75	--v12a Tweaked martial effect on levies - now base 75%, but each martial point gives 2.5%
NDefines.NMilitary.HOLDING_LEVY_SIZE_OWNER_MARTIAL_MULT = 0.025	-- Levy size modifier: Each point of the holding owner's Martial skill is multiplied with this and added to HOLDING_LEVY_SIZE_OWNER_MARTIAL_BASE
NDefines.NMilitary.MERCENARY_MAINTENANCE_FACTOR = 1				-- Maintenance factor for NORMAL mercenary units v12c +25% v15 now +100% of 0.5
NDefines.NMilitary.MERCENARY_VASSAL_MAINTENANCE_FACTOR = 1.25		-- Maintenance factor for VASSALIZED mercenary units v12c +25% v15 now 25% more expensive than normal
NDefines.NMilitary.MERCENARY_HIRE_COST_FACTOR = 0.15				-- Hire cost factor for mercenary units v15 now 25% cheaper than twice vanilla
NDefines.NMilitary.HOLY_ORDER_HIRE_COST_FACTOR = 0.333				-- Conversion of nominal gold cost to piety cost when hiring Holy Orders
NDefines.NMilitary.VASSAL_MERC_HIRE_COST_FACTOR = 0.75			-- Fraction of nominal hire cost when hiring vassal mercenaries OR Holy Orders
NDefines.NMilitary.MERCENARY_HIRE_DISTANCE_THRESHOLD = 500		-- Mercs will not be available if the province of origin is more distant from your capital
NDefines.NMilitary.BATTLE_WARSCORE_WORTH = 50						-- Warscore from battles are multiplied with this value v12 reduced to 100% maximum, so that an absolute victory is necessary to win the war early --v12(experiment) increased emphasis on sieging, so reduced to 50%
NDefines.NMilitary.MIN_LEVY_RAISE_OPINION_THRESHOLD = -50			-- Below this opinion value you'll get the least amount of troops possible v11 increased to 25 v12 lowered to 0 (vanilla was -25) v12a tweaked to -50, to increase emphasis on levies
NDefines.NMilitary.LEVY_PERCENT_BEFORE_CAN_RAISE = 10			-- Needs at least this much % of full levy before we can raise it
NDefines.NMilitary.PERCENT_OF_GARRISON_DETACHED = 0.333				-- This percent of the garrison is detached from the winning unit of a siege <-riknap: increased from 0.1 to 0.25 to minimise recapture v12 further increased to 33.3%
NDefines.NMilitary.NUM_DAYS_BETWEEN_SIEGE_MORALE_LOSS = 7		-- Number of days between morale loss for defender in a siege > v10 made to 1 week to increase pulses
NDefines.NMilitary.SIEGE_MORALE_LOSS = 0.16						-- Monthly morale loss in a siege > v10 reduced to compensate for above edit from original 0.2, and reduced further to 0.075 > v10c increased since it apparently is "monthly" as should have been obvious if I actually... read. Now essentially 9 months base siege time.	-> v10d recomputed to account for fort level [(FL+1)^-1]modifier, interestingly vanilla value of 0.2 at fort level 10 takes a year (no outnumber bonus). v10f increased to 0.3 for approximately 9 months base siege time. v12c reduced to 0.16
NDefines.NMilitary.DAYS_BETWEEN_COMBAT_EVENTS = 7				-- Combat events will happen every this many days  v11 frequency increased
NDefines.NMilitary.BATTLE_PRESTIGE_MULTIPLIER = 30				-- Total prestige gained in the battle will be this * ( losers losses ) / 1000 #libert3 v10 reduced from 30 to 20 v10n reduced to 15 v12 slightly increased to 20 v12a returned to vanilla
NDefines.NMilitary.BATTLE_TECH_MULTIPLIER = 0.45					-- Military tech gain from battles multiplier. v12a reduced to 0.45 (vanilla 0.5)
NDefines.NMilitary.REINFORCE_RATE = 0.0375							-- Reinforce rate per year > v10b lowered all reinforce rates v10d returned to vanilla v10e returned to 10b values
NDefines.NMilitary.MERC_REINFORCE_RATE = 0.01					-- The rate at which mercenaries and holy orders reinforce in the field v10b lowered as with other reinfrce rates v10k lowered from 0.75% to 0.5% v10k made zero v10n increased to 0.1% since it was reinforcing at peace-time even when raised anyway. v15 now 1% when active
NDefines.NMilitary.MERC_REINFORCE_RATE_WHEN_IDLE = 0.05			-- The rate at which mercenaries and holy orders reinforce when not hired <-riknap make them more useful and not always depleted all the time - raised 5 x v10b lowered as with all rates , now back to vanilla < v10d returned to 0.1 <v10k reduced to 0.5% v10l increased to 25% v10n reduced to 10% v15 now 5% when idle
NDefines.NMilitary.GARRISON_REINFORCE_RATE_MULTIPLIER = 2			-- The rate at which the garrison reinforce
NDefines.NMilitary.LEVY_RAISED_REINFORCE_RATE_MULTIPLIER = 0	-- The rate at which the garrison/levy reinforce when the levy is raised <- decreased to near nil to make raising your levy actually mean raising your men. The tiny multiplier is for trickle volunteers and to make train troops by martial not useless... not empirically useless anyway <- v9 attempt to make even smaller < v10d reduced to zero, as it was causing a bug of sorts.
NDefines.NMilitary.BATTLE_PIETY_MULTIPLIER = 1.5					-- Piety gain/loss multiplier. This is based on the prestige value, so a value of 1 gives a leader as much piety as he gains prestige from combat
NDefines.NMilitary.SIEGE_PIETY_MULTIPLIER = 0.15					-- Piety gain/loss multiplier for sieges v10n increased from 0.2 to 0.3 v11 reduced to 0.15
NDefines.NMilitary.CAPITAL_WARSCORE_MULTIPLIER = 1.5				-- Warscore multiplier for capital(this is scaled with SETTLEMENT_WARSCORE_MULTIPLIER) - v11 increased to 1.5 from 1
NDefines.NMilitary.SETTLEMENT_WARSCORE_MULTIPLIER = 1			-- Warscore worth for occupied private demesne -- v11 increased from 0.3 to 0.4 v12 increased to 1
NDefines.NMilitary.VASSAL_SETTLEMENT_WARSCORE_MULTIPLIER = 0.5	-- Warscore worth for occupied vassals 1 -- v11 decreased from 0.3 to 0.15 v12 lowered further to 0.5x
NDefines.NMilitary.CONTESTED_TERRITORY_WARSCORE_MULTIPLIER = 2.5	-- Multiplier for contested settlements v11 increased to 2.5x
NDefines.NMilitary.DAYS_UNTIL_HOLDER_GETS_WARSCORE_INDEP = 180		-- Days until the war score of the title owner starts increasing in Independence Wars, if he controls the Holdings v10l increased to 6 months
NDefines.NMilitary.CONTESTED_TITLE_OCCUPIED_WARSCORE_BONUS = 5	-- Amount of warscore per year since attacker/defender started getting the bonus
NDefines.NMilitary.CONTESTED_TITLE_OCCUPIED_WARSCORE_BONUS_INDEP = 40	-- Amount of warscore per year since attacker/defender started getting the bonus, for independence wars v10l 20->40
NDefines.NMilitary.DIFFERENT_RELIGIONGROUP_SUPPLY_PENALTY = -0.5	-- Only 50% supply in provinces with different religios group
NDefines.NMilitary.OWN_SETTLEMENT_SUPPLY_BONUS = 1				-- Extra supply from being in home realm v11 doubled
NDefines.NMilitary.NEUTRAL_SETTLEMENT_SUPPLY_BONUS = 0.5			-- Neutral supply bonus v11 ddoubled
NDefines.NMilitary.CONTROL_SETTLEMENT_SUPPLY_BONUS = 0.75			-- Supply bonus from occupied settlements v11 tripled to compenaste
NDefines.NMilitary.ENEMY_SETTLEMENT_SUPPLY_BONUS = -0.25			-- Supply bonus from enemy settlements(woot!) > v10 made -0.05 from 0 v11 increased to -25%
NDefines.NMilitary.NEARBY_SETTLEMENT_SINGLE_SUPPLY_BONUS = 0.5	-- Bonus for nearby settlement, if not controlling one yourself
NDefines.NMilitary.MAX_ATTRITION_LEADER_REDUCTION = -0.1			-- Center leader reduces max attrition(reduction in actual percent) --v12 tweaked to 0.15% (adjusted base attitions in static modifiers to compensate) v12a returned to 10%
NDefines.NMilitary.ATTRITION_LEVEL_FACTOR = 0.25					-- A general "attrition per month" multiplier --v12 reduced from 0.5 to 0.25
NDefines.NMilitary.ATTRITION_LEVEL_FACTOR_50_OVER = 1			-- A general "attrition per month" multiplier when 50% over the supply limit v12 returned to vanilla
NDefines.NMilitary.ATTRITION_LEVEL_FACTOR_100_OVER = 5			-- A general "attrition per month" multiplier when 100% over the supply limit v12 increased to 5 to whittle down large siege stacks
NDefines.NMilitary.PAGAN_HOME_SUPPLY_MOD = 0.15					-- Non Pagans suffer extreme attrition in some Pagan homelands (based on province religion) --v12 reduced to 15% from 5% to accomodate longer siege times
NDefines.NMilitary.NAVAL_ATTRITION = 0.03							-- Attrition taken monthly by units loaded on ships --v12 increased to 3%
NDefines.NMilitary.ARMY_MOVEMENT_SPEED = 5							-- Base movement speed of land units -v12 from 3 to 5 
NDefines.NMilitary.NAVY_MOVEMENT_SPEED = 15							-- Base movement speed of naval units --v11 from 30 to 20 v12 reduced to new vanilla levels of 15
NDefines.NMilitary.ARMY_LOAD_MOVE_COST = 40.0					-- Movement cost for moving armies onto fleets at sea.
NDefines.NMilitary.ARMY_UNLOAD_MOVE_COST = 40.0					-- Movement cost for moving armies off fleets at sea.
NDefines.NMilitary.OVERRUN_RATIO = 15								-- Ratio needed for total extermination of enemy units
NDefines.NMilitary.DAYS_BEFORE_DEFENDER_SALLY = 14					-- Number of days before defenders sally in a siege where they have superior numbers -> v10 changed to 14 for a while
NDefines.NMilitary.TOTAL_OCCUPATION_SCALE = 1.5					-- The % of occupation which gives you 100% warscore v11 increased to 1 -v12 increased further to 1.5
NDefines.NMilitary.ATTACKER_ASSULT_DAMAGE_FACTOR = 10				-- Attacker damage scale factor when assaulting <- make assaults weaker < v10: earlier versions completely misunderstood this. A higher value means assault takes more damage, not gives more damage. Made to x15 <v10c rebalanced to 10
NDefines.NMilitary.DEFENDER_ASSULT_DAMAGE_FACTOR = 0.555				-- Defender damage scale factor when assaulting
NDefines.NMilitary.FLANKING_DAMAGE_BONUS = 0.3					-- Percentage bonus when flanking in combat --v12 increased to 50% v12a reverted to 30% due to some bug (getting a 450% damage modifier when dual flanking)
NDefines.NMilitary.LEADER_MARTIAL_DAMAGE_BONUS = 0.03				-- Percentage bonus to damage for each point of martial the flank leader has v12 increased effect to 7.5% v12a reduced to 3%
NDefines.NMilitary.WAR_CONTRIBUTION_BATTLE_PER_DAY = 0.50			-- Every day in battle, a participant gets this. (My Troops / Total Friendly Troops) * Total Enemy Troops * WAR_CONTRIBUTION_BATTLE_PER_DAY. Max is [My Troops]. --v12 increased battle worth
NDefines.NMilitary.LOW_DECADENCE_MORALE_MOD = 0.5					-- Extra Morale defence when at 0% decadence
NDefines.NMilitary.HIGH_DECADENCE_MORALE_MOD = -2.0				-- Extra Morale damage taken when at 100% decadence
NDefines.NMilitary.EVENT_TROOPS_SIZE_MULT = 0.5							-- Applied to match_mult to determine size of troops spawned from events & history v12a reduced to 50% (since garrison sizes were retained but levy effects from buildings reduced ten-fold)
NDefines.NMilitary.LOOT_TAX_MULTIPLIER = 2						-- Base gold looted from raided holdings is (tax * LOOT_TAX_MULTIPLIER) + (total building value * LOOT_BUILDING_MULTIPLIER)
NDefines.NMilitary.LOOT_HOLDING_DEST_MIN_SAFE = 50					-- there is a 1 in LOOT_HOLDING_DESTRUCTION_ODDS chance that
NDefines.NMilitary.LOOT_HOLDING_DESTRUCTION_ODDS = 200				-- a holding with less than LOOT_HOLDING_DEST_MIN_SAFE buildings will be destroyed by looting
NDefines.NMilitary.LOOT_HOLDING_BUILDING_DEST_ODDS = 1			-- there is a 1 in this chance a random building is destroyed when looted
NDefines.NMilitary.RETINUE_FROM_REALMSIZE = 0					--RIKNAP'S VALUE: 0
NDefines.NMilitary.RETINUE_TITLE_MODIFIER = 0.5					
NDefines.NMilitary.RETINUE_HIRE_COST_MULTIPLIER = 0.25			--RIKNAP'S VALUE: 0.25-- Retinues are free to hire atm, but they cost alot to reinforce
NDefines.NMilitary.RETINUE_REINFORCE_COST = 0.333					-- RIKNAP'S VALUE: 0.333 --Retinues cost while reinforcing.
NDefines.NMilitary.RETINUE_CONSTANT_COST = 0.333 					-- RIKNAP'S VALUE: 0.333 --- Retinues cost at all times.
NDefines.NMilitary.TERRAIN_SPEC_BONUS = 0.5						-- Bonus to fighting in this terrain if you have that terrain as your terrain specialization ( gained through combat events in that terrain ) --v12 increased to 50%
NDefines.NMilitary.LIEGE_LEVY_REINF_RATE = 0.0375				-- v10b lowered reinf all around <v10d returned to vanilla
NDefines.NMilitary.LIEGE_LEVY_SIZE_MULTIPLIER = 0.75				-- The Size of the liege levy will be the total troops in the vassal subrealm * this --v12a Increased liege levy to 75% to skew importance to the top-liege's role
NDefines.NMilitary.LIEGE_LEVY_COST_MULTIPLIER = 0.25				-- The vassal will pay regular maintenance * this for the liege levy
NDefines.NMilitary.LIGHT_INFANTRY_MORALE = 3
NDefines.NMilitary.LIGHT_INFANTRY_MAINTENANCE = 1
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_ATTACK = 4
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_ATTACK = 3
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_ATTACK = 3
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_DEFENSE = 3
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_DEFENSE = 3
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_DEFENSE = 4
NDefines.NMilitary.HEAVY_INFANTRY_MORALE = 5
NDefines.NMilitary.HEAVY_INFANTRY_MAINTENANCE = 2
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_ATTACK = 1
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_MELEE_ATTACK = 8
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_ATTACK = 2
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_DEFENSE = 6
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_DEFENSE = 3
NDefines.NMilitary.HEAVY_INFANTRY_GRAPHICAL_FACTOR = 2
NDefines.NMilitary.PIKEMEN_MORALE = 5 -- prev 6
NDefines.NMilitary.PIKEMEN_PHASE_MELEE_ATTACK = 6.9
NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_ATTACK = 1
NDefines.NMilitary.PIKEMEN_PHASE_SKIRMISH_DEFENSE = 6
NDefines.NMilitary.PIKEMEN_PHASE_MELEE_DEFENSE = 8
NDefines.NMilitary.PIKEMEN_GRAPHICAL_FACTOR = 2
NDefines.NMilitary.LIGHT_CAVALRY_MORALE = 4
NDefines.NMilitary.LIGHT_CAVALRY_MAINTENANCE = 2.5
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_ATTACK = 5
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_ATTACK = 4.5
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_ATTACK = 12
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_DEFENSE = 6
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_DEFENSE = 4
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_DEFENSE = 6
NDefines.NMilitary.LIGHT_CAVALRY_GRAPHICAL_FACTOR = 2.5
NDefines.NMilitary.KNIGHTS_MORALE = 8
NDefines.NMilitary.KNIGHTS_MAINTENANCE = 5
NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_ATTACK = 9
NDefines.NMilitary.KNIGHTS_PHASE_SKIRMISH_DEFENSE = 6
NDefines.NMilitary.KNIGHTS_PHASE_MELEE_DEFENSE = 7
NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_DEFENSE = 5
NDefines.NMilitary.KNIGHTS_GRAPHICAL_FACTOR = 5
NDefines.NMilitary.ARCHERS_MORALE = 3
NDefines.NMilitary.ARCHERS_MAINTENANCE = 1
NDefines.NMilitary.ARCHERS_PHASE_SKIRMISH_ATTACK = 8
NDefines.NMilitary.ARCHERS_PHASE_MELEE_ATTACK = 3
NDefines.NMilitary.ARCHERS_PHASE_MELEE_DEFENSE = 3
NDefines.NMilitary.ARCHERS_PHASE_PURSUE_DEFENSE = 3
NDefines.NMilitary.SPECIAL_TROOPS_MORALE = 8
NDefines.NMilitary.SPECIAL_TROOPS_MAINTENANCE = 4
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_SKIRMISH_ATTACK = 8
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_PURSUE_ATTACK = 8
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_MELEE_DEFENSE = 3
NDefines.NMilitary.SPECIAL_TROOPS_GRAPHICAL_FACTOR = 1
NDefines.NMilitary.GALLEYS_MAINTENANCE = 50
NDefines.NMilitary.COMMAND_MODIFIER_MARTIAL_MULTIPLIER = 0.03 --v12a reduced from 5% to 3%
NDefines.NMilitary.MAX_RIVER_MOVEMENT_FORT_LEVEL = 80.0 -- v12 increased from 10 to 80 since this is the sum of total fort level adjacent to a river based on current estimates (ie. 8+5+3 for all holding types x 5 approx border counties )
NDefines.NMilitary.BOTTLENECK_DEFENDER_MARTIAL_MODIFIER = 1.25--v12a increased Defender Bottleneck modifier by 25%
NDefines.NMilitary.CAPITAL_DUCHY_LEVY_MULT = 1.25 --Vassals in your capital's de-jure-duchy give 100% of liege levy, in de-jure-kingdom get 90% of liege levy, and de-jure-empire get 75% of liege levy. 
NDefines.NMilitary.CAPITAL_DUCHY_LIEGE_LEVY_MULT = 1
NDefines.NMilitary.CAPITAL_KINGDOM_LIEGE_LEVY_MULT = 0.9
NDefines.NMilitary.CAPITAL_EMPIRE_LIEGE_LEVY_MULT = 0.5
NDefines.NMilitary.OUTSIDE_LIEGE_LEVY_MULT = 0.5				-- Multiplier to liege levies outside all capital regions
NDefines.NMilitary.SUPPLY_CAPACITY = 62						-- Amount of days of worth supply that a unit can hold. - v14 doubled
NDefines.NMilitary.OUT_OF_SUPPLY_ATTRITION_BASE = 0.002		-- The attrition a unit that is out of supply takes. -- v14 doubled
NDefines.NMilitary.OUT_OF_SUPPLY_ATTRITION_INCREASE = 0.0002	-- The increase per tick of attrition a unit that is out of supply takes. --v14 doubled
NDefines.NMilitary.MAJOR_BATTLE_WARSCORE = 5.0					-- The minium warscore gain needed for a battle to be considered major
NDefines.NTechnology.DONT_EXECUTE_TECH_BEFORE = 1066				-- Set this to your earliest starting year
NDefines.NTechnology.POINTS_PER_ATTRIBUTE = 0.015				-- v12 decreased from 0.04 to 0.015 to slow down tech 
NDefines.NTechnology.MAX_DEMESNE_BONUS = 1 					-- maximum bonus from demesne v12 increased max bonus to 100%
NDefines.NTechnology.TRADEPOST_SPREAD_BONUS = 0.01 			-- Spread from trade posts v12 increased from .2% to 1%
NDefines.NTechnology.SPYACTION_SPREAD_BONUS = 0.025				-- Spread from the target of the study technology spymaster action --v12 increased to 2.5%
NDefines.NTechnology.IDEAL_YEAR_LEVEL_0 = 1000 					-- the chance to get a progress to this level will increase after this date and decrease before it v12 changed from default to year 1000
NDefines.NTechnology.IDEAL_YEAR_LEVEL_8 = 1800 -- v12: 100 year gap
NDefines.NTechnology.IDEAL_YEAR_AHEAD_PENALTY_INVEST = 0.5		-- Percent increase in cost pre level ahead of ideal date -- v12 from 0.3 to 0.5
NDefines.NDisease.SMALL_TOWN_INCOME = 20.0 -- A coastal town with this income has no chance of starting an outbreak v12 increased from 11
NDefines.NDisease.BIG_TOWN_INCOME = 50.0 -- A coastal town with this income is always a canditate [sic] for starting an outbreak v12 increased from 30
NDefines.NDisease.MIN_OUTBREAK_CHANCE = 0.25 -- Min chance that an outbreak will happen in a particular town v12 increased from 10%
NDefines.NAI.INTERACTION_OPINION_CHANGE_TO_DISCARD_REJECTION = 20	-- AI will reevalute offers if opinion has changed by at least this amount, regardless of time left
NDefines.NAI.NAVAL_INVASION_RANGE = 50								-- Factor which increase AI invasion range if set higher --v12 reduced to half (might be vestigial as well anyway )
NDefines.NAI.DOW_AGGRESSION_FACTOR = 0.5							-- General aggressiveness declarations of war v10l decreased from 0.5 to 0.25 v12 returned to vanilla
NDefines.NAI.REVOLT_AGGRESSION_FACTOR = 0.75						-- General aggressiveness for revolts against the liege v10l decreased from 0.75 to 0.375 v11 returned to 0.75
NDefines.NAI.REVOLT_DISTANCE_FACTOR = 2.0							-- Multiplier for how much distance from capital affects independence minded revolters v10l increased from 0.5 to 2.0 v11 returned to default v12 increased to 2.0 again (might not have an effect, but might as well anyway)
NDefines.NAI.REVOLT_OTHER_INDEP_RISK = 20							-- Each ongoing other independence revolt increases revolt risk by this amount for all independence-minded revolters
NDefines.NAI.REVOLT_OTHER_INDEP_RISK_CAP = 100						-- Cap to the total risk from the above
NDefines.NAI.MAX_EMPIRE_TITLES_TO_CREATE = 1						-- AI will not seek to create/usurp more Empire-level titles than this (0 for unlimited) - v11 only 1 empire max
NDefines.NAI.AI_EMPEROR_CREATES_KINGDOMS = 1						-- If set to 1, AI Emperors will create King-level titles --v12 turned on
NDefines.NAI.DESIRED_CONSORTS = 2									-- AI will always want at least this many concubines, if they lack sons v12c increased to 1
NDefines.NAI.RAID_MAX_REALM_SIZE = 100								-- Realms with more holdings than this will never go on Raids
NDefines.NAI.RAID_AGGRESSION = 15									-- General frequency of raids. A LOWER number means more often!
NDefines.NAI.RAID_PREP_INV_SPARE_SAME_CULTURE = 0					-- AI of religions that allow prepared invasions will not raid provinces in their own culture group (to prevent intra-Scandinavian raids) v12c disabled
NDefines.NAI.RAID_SPARE_ACCEPTED_RELIGIONS = 0						-- AI will not raid rulers of other religions in the same religion group, unless heresy vs parent religion
NDefines.NAI.TRIBAL_REPUBLIC_MIDAS_TOUCHED_MODIFIER = 20			-- How much the midas touched trait counts toward the threshold above
NDefines.NAI.TRIBAL_PRESTIGE_CALL_TRESHOLD = -100 					-- The treshold needed for the AI to start considering answering call to not take the prestige hit
NDefines.NFrontend.CAMERA_LOOKAT_X = 2750.0 			-- Rotation point in main menu v12 vanilla = 790 now 1850 v15 2750 ganges
NDefines.NFrontend.CAMERA_LOOKAT_Y = 25.0
NDefines.NFrontend.CAMERA_LOOKAT_Z = 1900.0 --v12 vanilla = 1000 v15 1200
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_X = 850.0  -- Rotation point in settings --v12 1280
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_Y = 5.0		-- Y is height v15 vanilla 0
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_Z = 2200.0 --v12 850, old. 648, vanilla
NDefines.NFrontend.CAMERA_START_X = 2750.0				-- Initial position in main menu v15 ganges 2750
NDefines.NFrontend.CAMERA_START_Y = 100.0				-- Y is height
NDefines.NFrontend.CAMERA_START_Z = 900.0 --v15 below ganges (1200)
NDefines.NFrontend.CAMERA_END_X = 875.0				-- Move to position in main menu v12 790 default now 1225 v15
NDefines.NFrontend.CAMERA_END_Y = 50.0 --v12 500 default
NDefines.NFrontend.CAMERA_END_Z = 2200.0 --v12 600 default v15 1200
NDefines.NFrontend.CAMERA_MIN_DIST_FOR_ROTATE = 1500.0 -- Controls when rotation starts. When camera is close enough it starts v12 prev 800?
NDefines.NFrontend.TIME_FROZEN = 2.5  				-- Time before initial animation starts (some delay here so it should NOT be 0, then the animation starts before you can see it)
NDefines.NFrontend.TIME_UNTIL_ROTATE = 5 			-- Time when rotation start (from beginning of time)
NDefines.NFrontend.CAMERA_SPEED_START = 0.02  			-- Initial animation speed v12 previously 0.04?
NDefines.NFrontend.CAMERA_SPEED_ROTATE = 0.02			-- Rotation speed
NDefines.NFrontend.GUI_MOVE_SPEED = 200				-- How fast sliding gui objects move ( pixels/s ) v12 300 default (stuff like the new game menu's) v15 225 (no real reason)
NDefines.NFrontend.FADE_IN_DONE_TIME = 2 --v12  2.2 default
NDefines.NFrontend.GUI_START_MOVE_TIME = 2.5
NDefines.NFrontend.CAMERA_START_MOVE_TIME = 2.5 --v12 3.0 default
NDefines.NFrontend.CAMERA_SPEED_IN_MENUS = 0.02 --v12 0.4 default - the sweeping speed
NDefines.NFrontend.FRONTEND_POS_X = 875.0 -- v12 790 default now 1425
NDefines.NFrontend.FRONTEND_POS_Y = 115.0 -- v12 500 default now 115
NDefines.NFrontend.FRONTEND_POS_Z = 1900.0 -- v12 600 default now 750
NDefines.NFrontend.FRONTEND_LOOK_X = 850.0--v12 790 default now 1280
NDefines.NFrontend.FRONTEND_LOOK_Y = 5.0  --v12 0 default no 35
NDefines.NFrontend.FRONTEND_LOOK_Z = 2200.0  --v12 1000 default now 865
NDefines.NFrontend.SETTINGS_POS_X = 875.0 -- v15 vanilla 1300
NDefines.NFrontend.SETTINGS_POS_Y = 200.0 -- v15 vanilla 200
NDefines.NFrontend.SETTINGS_POS_Z = 1900.0 --v15 vanilla 700
NDefines.NFrontend.SETTINGS_LOOK_X = 850.0 -- v15 vanilla 1280
NDefines.NFrontend.SETTINGS_LOOK_Y = 5.0		-- v15 vanilla 0
NDefines.NFrontend.SETTINGS_LOOK_Z = 2200.0 -- v15 vanilla 900
NDefines.NFrontend.MP_OPTIONS_POS_X = 875.0 --v15 vanilla 360
NDefines.NFrontend.MP_OPTIONS_POS_Y = 115.0 --v15 vanilla 200
NDefines.NFrontend.MP_OPTIONS_POS_Z = 1900.0 --v15 vanilla 848
NDefines.NFrontend.MP_OPTIONS_LOOK_X = 850.0 --v15 vanilla 490
NDefines.NFrontend.MP_OPTIONS_LOOK_Y = 5.0	-- v15 vanilla 0%
NDefines.NFrontend.MP_OPTIONS_LOOK_Z = 2200.0 --v15 vanilla 1200
NDefines.NFrontend.TUTORIAL_POS_X = 875.0 --v15 vanilla 600
NDefines.NFrontend.TUTORIAL_POS_Y = 115.0 --v15 vanilla 150
NDefines.NFrontend.TUTORIAL_POS_Z = 1900.0 --v15 vanilla 1248
NDefines.NFrontend.TUTORIAL_LOOK_X = 850.0 --v15 vanilla 450
NDefines.NFrontend.TUTORIAL_LOOK_Y = 5.0	 --v15 vanilla 0%
NDefines.NFrontend.TUTORIAL_LOOK_Z = 2200.0 --v15 vanilla 1398
NDefines.NFrontend.CREDITS_POS_X = 875.0 --v15 vanilla 1000
NDefines.NFrontend.CREDITS_POS_Y = 115.0 -- v15 vanilla 200
NDefines.NFrontend.CREDITS_POS_Z = 2000.0 -- v15 vanilla 1308
NDefines.NFrontend.CREDITS_LOOK_X = 850.0 -- v15 vanilla 900
NDefines.NFrontend.CREDITS_LOOK_Y = 5.0	 -- v15 vanilla 0
NDefines.NFrontend.CREDITS_LOOK_Z = 2200.0 -- v15 vanilla 1450
NDefines.NEndGame.DYN1_ID = 1100244
NDefines.NEndGame.DYN2_ID = 1100101
NDefines.NEndGame.DYN3_ID = 1100262
NDefines.NEndGame.DYN4_ID = 1100159
NDefines.NEndGame.DYN5_ID = 1100407
NDefines.NEndGame.DYN6_ID = 1100265
NDefines.NEndGame.DYN7_ID = 1100266
NDefines.NEndGame.DYN8_ID = 1100201
NDefines.NEndGame.DYN9_ID = 1100150
NDefines.NEndGame.DYN10_ID = 1100103
NDefines.NEndGame.DYN11_ID = 1100237
NDefines.NEndGame.DYN12_ID = 1100381
NDefines.NEndGame.DYN13_ID = 1100106
NDefines.NEndGame.DYN14_ID = 1100498
NDefines.NEndGame.DYN15_ID = 1100164
NDefines.NRulerDesigner.BASE_ATTRIB = 6
NDefines.NRulerDesigner.COST_SON = 2.0
NDefines.NRulerDesigner.COST_FERTILITY = 10.0
NDefines.NRulerDesigner.COST_HEALTH = 5.0
NDefines.NRulerDesigner.COST_MONTHLY_PRESTIGE = 5.0
NDefines.NRulerDesigner.COST_MONTHLY_PIETY = 10.0
NDefines.NRulerDesigner.COST_MONTHLY_WEALTH = 5.0
NDefines.NRulerDesigner.COST_LIEGE_OPINION = -0.5
NDefines.NRulerDesigner.COST_INFIDEL_OPINION = 0.5
NDefines.NRulerDesigner.COST_AMBITION_OPINION = -0.25
NDefines.NLearningScenario.START_CHARACTER = 710
NDefines.NLearningScenario.ANGRY_VASSAL = 712
NDefines.NLearningScenario.REVOLT_PROVINCE = 163
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_ENABLED = 0
